doctrine:
  dbal:
    types:
        status: Backend\Modules\Examples\Domain\DBALType\StatusDBALType
  orm:
    mappings:
      Example:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Examples/Domain/Entity"
        alias: Example
        prefix: Backend\Modules\Examples\Domain\Entity

